export const CID11_MENTAL_HEALTH = [
  {"c":"6A00","n":"Transtornos mentais, comportamentais e de desenvolvimento neurológico são sín...","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A00.0","n":"Transtorno de desenvolvimento intelectual, leve","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A00.1","n":"Transtorno de desenvolvimento intelectual, moderada","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A00.2","n":"Transtorno de desenvolvimento intelectual, grave","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A00.3","n":"Transtorno de desenvolvimento intelectual, profundo","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A00.4","n":"Transtorno de desenvolvimento intelectual, provisória","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A00.Z","n":"Transtornos do desenvolvimento intelectual, não especificado","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A01","n":"Distúrbios da fala ou de desenvolvimento de linguagem","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A01.0","n":"Desordem som da fala do desenvolvimento","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A01.1","n":"Distúrbio de fluência da fala de desenvolvimento","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A01.2","n":"Distúrbio de linguagem de desenvolvimento","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A02","n":"Transtorno do espectro do autismo","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A05","n":"Transtorno do déficit de atenção com hiperatividade","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A20","n":"Esquizofrenia","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A60","n":"Transtorno bipolar tipo I","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A70","n":"Transtorno depressivo episódio único","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6A71","n":"Transtorno depressivo recorrente","g":"Transtornos do Neurodesenvolvi"},
  {"c":"6B00","n":"Transtorno de ansiedade generalizada","g":"Esquizofrenia, Transtornos de "},
  {"c":"6B01","n":"O transtorno do pânico","g":"Esquizofrenia, Transtornos de "},
  {"c":"6B20","n":"Transtorno obsessivo-compulsivo","g":"Esquizofrenia, Transtornos de "},
  {"c":"6B40","n":"Perturbação de Stress Pós-traumático","g":"Esquizofrenia, Transtornos de "},
  {"c":"6B80","n":"Anorexia Nervosa","g":"Esquizofrenia, Transtornos de "},
  {"c":"6B81","n":"Bulimia Nervosa","g":"Esquizofrenia, Transtornos de "},
  {"c":"6C40","n":"Transtornos devido ao uso de álcool","g":"Transtornos por Uso de Substân"},
  {"c":"6D80","n":"Demência associada à doença de Alzheimer","g":"Transtornos de Personalidade e"}
];
